# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/downloader.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'protos/downloader.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17protos/downloader.proto\x12\ndownloader\"\x07\n\x05\x45mpty\"\"\n\x0fVersionResponse\x12\x0f\n\x07version\x18\x01 \x01(\t\"G\n\x0eUpdateResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x13\n\x0bnew_version\x18\x03 \x01(\t\"_\n\x0f\x44ownloadRequest\x12\x0b\n\x03url\x18\x01 \x01(\t\x12\x10\n\x08is_music\x18\x02 \x01(\x08\x12\x14\n\x0cvideo_height\x18\x03 \x01(\x05\x12\x17\n\x0f\x63ookies_content\x18\x04 \x01(\t\"\x83\x01\n\x08Metadata\x12\r\n\x05title\x18\x01 \x01(\t\x12\x10\n\x08uploader\x18\x02 \x01(\t\x12\x13\n\x0bwebpage_url\x18\x03 \x01(\t\x12\x10\n\x08\x64uration\x18\x04 \x01(\x05\x12\r\n\x05width\x18\x05 \x01(\x05\x12\x0e\n\x06height\x18\x06 \x01(\x05\x12\x10\n\x08\x66ilename\x18\x07 \x01(\t\"x\n\x10\x44ownloadResponse\x12(\n\x08metadata\x18\x01 \x01(\x0b\x32\x14.downloader.MetadataH\x00\x12\x14\n\nfile_chunk\x18\x02 \x01(\x0cH\x00\x12\x19\n\x0fthumbnail_chunk\x18\x03 \x01(\x0cH\x00\x42\t\n\x07payload2\xe3\x01\n\x11\x44ownloaderService\x12N\n\rDownloadMedia\x12\x1b.downloader.DownloadRequest\x1a\x1c.downloader.DownloadResponse\"\x00\x30\x01\x12>\n\nGetVersion\x12\x11.downloader.Empty\x1a\x1b.downloader.VersionResponse\"\x00\x12>\n\x0bUpdateYtdlp\x12\x11.downloader.Empty\x1a\x1a.downloader.UpdateResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.downloader_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=39
  _globals['_EMPTY']._serialized_end=46
  _globals['_VERSIONRESPONSE']._serialized_start=48
  _globals['_VERSIONRESPONSE']._serialized_end=82
  _globals['_UPDATERESPONSE']._serialized_start=84
  _globals['_UPDATERESPONSE']._serialized_end=155
  _globals['_DOWNLOADREQUEST']._serialized_start=157
  _globals['_DOWNLOADREQUEST']._serialized_end=252
  _globals['_METADATA']._serialized_start=255
  _globals['_METADATA']._serialized_end=386
  _globals['_DOWNLOADRESPONSE']._serialized_start=388
  _globals['_DOWNLOADRESPONSE']._serialized_end=508
  _globals['_DOWNLOADERSERVICE']._serialized_start=511
  _globals['_DOWNLOADERSERVICE']._serialized_end=738
# @@protoc_insertion_point(module_scope)
