# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from protos import downloader_pb2 as protos_dot_downloader__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in protos/downloader_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DownloaderServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DownloadMedia = channel.unary_stream(
                '/downloader.DownloaderService/DownloadMedia',
                request_serializer=protos_dot_downloader__pb2.DownloadRequest.SerializeToString,
                response_deserializer=protos_dot_downloader__pb2.DownloadResponse.FromString,
                _registered_method=True)
        self.GetVersion = channel.unary_unary(
                '/downloader.DownloaderService/GetVersion',
                request_serializer=protos_dot_downloader__pb2.Empty.SerializeToString,
                response_deserializer=protos_dot_downloader__pb2.VersionResponse.FromString,
                _registered_method=True)
        self.UpdateYtdlp = channel.unary_unary(
                '/downloader.DownloaderService/UpdateYtdlp',
                request_serializer=protos_dot_downloader__pb2.Empty.SerializeToString,
                response_deserializer=protos_dot_downloader__pb2.UpdateResponse.FromString,
                _registered_method=True)


class DownloaderServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def DownloadMedia(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetVersion(self, request, context):
        """Новые методы
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateYtdlp(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DownloaderServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DownloadMedia': grpc.unary_stream_rpc_method_handler(
                    servicer.DownloadMedia,
                    request_deserializer=protos_dot_downloader__pb2.DownloadRequest.FromString,
                    response_serializer=protos_dot_downloader__pb2.DownloadResponse.SerializeToString,
            ),
            'GetVersion': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVersion,
                    request_deserializer=protos_dot_downloader__pb2.Empty.FromString,
                    response_serializer=protos_dot_downloader__pb2.VersionResponse.SerializeToString,
            ),
            'UpdateYtdlp': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateYtdlp,
                    request_deserializer=protos_dot_downloader__pb2.Empty.FromString,
                    response_serializer=protos_dot_downloader__pb2.UpdateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'downloader.DownloaderService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('downloader.DownloaderService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DownloaderService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def DownloadMedia(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/downloader.DownloaderService/DownloadMedia',
            protos_dot_downloader__pb2.DownloadRequest.SerializeToString,
            protos_dot_downloader__pb2.DownloadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetVersion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/downloader.DownloaderService/GetVersion',
            protos_dot_downloader__pb2.Empty.SerializeToString,
            protos_dot_downloader__pb2.VersionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateYtdlp(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/downloader.DownloaderService/UpdateYtdlp',
            protos_dot_downloader__pb2.Empty.SerializeToString,
            protos_dot_downloader__pb2.UpdateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
